name = "cf2dns"
main = "src/worker/index.ts"
compatibility_date = "2024-12-18"
compatibility_flags = ["nodejs_compat"]

# 环境变量
[vars]
ENVIRONMENT = "development"
JWT_SECRET = "your-jwt-secret-here"
CORS_ORIGIN = "*"

# D1 数据库配置
[[d1_databases]]
binding = "DB"
database_name = "cf2dns-db"
database_id = "your-database-id-here"

# KV 存储配置 (用于会话管理)
[[kv_namespaces]]
binding = "SESSIONS"
id = "your-kv-namespace-id-here"

# 生产环境配置
[env.production]
vars = { ENVIRONMENT = "production", CORS_ORIGIN = "https://your-domain.com" }

[[env.production.d1_databases]]
binding = "DB"
database_name = "cf2dns-db-prod"
database_id = "your-prod-database-id-here"

[[env.production.kv_namespaces]]
binding = "SESSIONS"
id = "your-prod-kv-namespace-id-here"

# 开发环境配置
[env.development]
vars = { ENVIRONMENT = "development", CORS_ORIGIN = "*" }

# 静态资源配置
[assets]
directory = "./dist"
binding = "ASSETS"

# 路由配置
[[routes]]
pattern = "your-domain.com/*"
zone_name = "your-domain.com"

# 限制配置
[limits]
cpu_ms = 50
