name = "cf2dns"
main = "src/worker/index.ts"
compatibility_date = "2024-12-18"
compatibility_flags = ["nodejs_compat"]

# 环境变量
[vars]
ENVIRONMENT = "preview"
JWT_SECRET = "cf2dns_jwt_2024_a8b9c7d4e5f6g1h2i3j4k5l6m7n8o9p0"
CORS_ORIGIN = "*"

# D1 数据库配置 (临时禁用以解决wrangler问题)
# [[d1_databases]]
# binding = "DB"
# database_name = "cf2dns"
# database_id = "e7a37f5e-0711-4b83-a5f7-c7dfeb901abe"

# KV 存储配置 (临时禁用以解决wrangler问题)
# [[kv_namespaces]]
# binding = "SESSIONS"
# id = "58dfc57f847941a29902f9e139332690"

# 生产环境配置 (暂时禁用，需要先创建资源)
# [env.production]
# vars = { ENVIRONMENT = "production", CORS_ORIGIN = "https://your-domain.com" }

# [[env.production.d1_databases]]
# binding = "DB"
# database_name = "cf2dns-db-prod"
# database_id = "PLACEHOLDER_PROD_DATABASE_ID"

# [[env.production.kv_namespaces]]
# binding = "SESSIONS"
# id = "PLACEHOLDER_PROD_KV_NAMESPACE_ID"

# 预览环境配置 (暂时禁用，需要先创建资源)
# [env.preview]
# vars = { ENVIRONMENT = "preview", CORS_ORIGIN = "*" }

# [[env.preview.d1_databases]]
# binding = "DB"
# database_name = "cf2dns-db-preview"
# database_id = "PLACEHOLDER_PREVIEW_DATABASE_ID"

# [[env.preview.kv_namespaces]]
# binding = "SESSIONS"
# id = "PLACEHOLDER_PREVIEW_KV_NAMESPACE_ID"

# 静态资源配置
[assets]
directory = "./dist"
binding = "ASSETS"

# 路由配置 (可选，用于自定义域名)
# [[routes]]
# pattern = "your-domain.com/*"
# zone_name = "your-domain.com"

# 兼容性设置已在第4行定义

# 限制配置 (免费计划不支持 CPU 限制)
# [limits]
# cpu_ms = 50
