name: Build Docker Image

on:
  push:
    branches: [ main, master ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Compute meta (tags and push flag)
        id: meta
        shell: bash
        run: |
          set -euo pipefail
          PUSH=false
          if [[ -n "${DOCKERHUB_USERNAME}" && -n "${DOCKERHUB_TOKEN}" ]]; then
            PUSH=true
          fi

          if [[ -n "${IMAGE_NAME}" ]]; then
            TAGS="$IMAGE_NAME"
          elif [[ -n "${DOCKERHUB_USERNAME}" ]]; then
            TAGS="${DOCKERHUB_USERNAME}/cf2dns:latest"
          else
            TAGS="cf2dns:latest"
          fi

          echo "push=$PUSH" >> "$GITHUB_OUTPUT"
          echo "tags=$TAGS" >> "$GITHUB_OUTPUT"

      - name: Login to Docker Hub
        if: ${{ steps.meta.outputs.push == 'true' }}
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Build (and optionally push)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ steps.meta.outputs.push == 'true' }}
          tags: ${{ steps.meta.outputs.tags }}
